# Database
spring.datasource.url=jdbc:postgresql://localhost:5435/advpro_2026
spring.datasource.username=root
spring.datasource.password=

# Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

